# -*- coding: utf-8 -*-
"""SpamEmailClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OWX8c1lWeJ3TOgAy8trmdoERezvimRN

# Spam Email Classifier using Machine Learning

## Project Description
This project demonstrates a simple Machine Learning approach to classify emails as **Spam** or **Ham (Not Spam)**.
The Naive Bayes algorithm is used along with basic text preprocessing techniques.

## Objectives
- To understand text classification
- To apply Naive Bayes algorithm
- To analyze model performance using accuracy

## Tools Used
- Python
- Pandas
- Scikit-learn
- Google Colab
"""

# Spam Email Classifier using Naive Bayes
# Mini Machine Learning Project

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Sample email dataset
emails = [
    "Win a free iPhone now",
    "Limited time offer claim prize",
    "Meeting scheduled at 10 am",
    "Project discussion tomorrow",
    "Congratulations you won lottery",
    "Please find attached report"
]

labels = ["spam", "spam", "ham", "ham", "spam", "ham"]

# Create DataFrame
data = pd.DataFrame({
    "email": emails,
    "label": labels
})

print("Total emails:", len(data))

# Text vectorization
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data["email"])
y = data["label"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# Train model
model = MultinomialNB()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Test with new email
test_email = ["Free prize waiting for you"]
test_vector = vectorizer.transform(test_email)

print("Test Email:", test_email[0])
print("Prediction:", model.predict(test_vector)[0])

# Spam Email Classifier using Naive Bayes
# Mini Machine Learning Project

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Sample email dataset
emails = [
    "Win a free iPhone now",
    "Limited time offer claim prize",
    "Meeting scheduled at 10 am",
    "Project discussion tomorrow",
    "Congratulations you won lottery",
    "Please find attached report"
]

labels = ["spam", "spam", "ham", "ham", "spam", "ham"]

# Create DataFrame
data = pd.DataFrame({
    "email": emails,
    "label": labels
})

print("Total emails:", len(data))

# Text vectorization
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data["email"])
y = data["label"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

# Train model
model = MultinomialNB()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Test with new email
test_email = ["Free prize waiting for you"]
test_vector = vectorizer.transform(test_email)

print("Test Email:", test_email[0])
print("Prediction:", model.predict(test_vector)[0])

"""## Conclusion
In this project, a simple spam email classifier was developed using the Naive Bayes algorithm.
The project helped in understanding text preprocessing, model training, and evaluation.
This approach can be extended using larger datasets and advanced NLP techniques.

"""